# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3caf9115045befbb9beb5262f1f13238e0d9e6369d9e521345da09fd2dfa015360b441b6c49c882d9bdc8e1454482b54896a4dd7849af61fb47561022476682e

test:
  secret_key_base: 48a64ca38bb76b6340d8bc22ecc727d46e91c0e873ae5ca4192e91da8fc395ffdb17637a8ffbcd627e85f929130ab7c87dde96602b80edaf5d0a3b660dedf55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
